version: '3'
services:

  debian8:
    build:
      context: .
      dockerfile: debian8/Dockerfile
    volumes:
    - ./output/debian8:/opt/build
    - ./sources:/opt/sources

  debian9:
    build:
      context: .
      dockerfile: debian9/Dockerfile
    volumes:
    - ./output/debian9:/opt/build
    - ./sources:/opt/sources
