#!/usr/bin/env bash

# package name
swname="ilmbase"
# download version
downloadver="2.3.0"
# package version
swver="2.3.0"

# build functions

__get_source_code() {
   [ -d "${swname}-${swver}-debian" ] || \
      die "no such folder: $PWD/${swname}-${swver}-debian"

   echo "** - removing the folder ${swname}-${swver} ..."
   rm -fr "${swname}-${swver}"

   echo "** - download the ${swname}  with tag v${downloadver} ..."
   wget https://github.com/openexr/openexr/releases/download/v${downloadver}/${swname}-${downloadver}.tar.gz -O ${swname}_${swver}.orig.tar.gz

   tar -zxvf ${swname}_${swver}.orig.tar.gz
   [ -d "${swname}-${downloadver}" ] || \
      die "no such folder: $PWD/${swname}-${downloadver}"

#   mv "${swname}-${downloadver}" "${swname}-${swver}"
#   [ -d "${swname}-${swver}" ] || \
#      die "no such folder: $PWD/${swname}-${swver}"

   # create the original tarball which is expected by debuild
   #tar -zcf ${swname}_${swver}.orig.tar.gz \
   #   ${swname}-${swver}

   cp -pr "${swname}-${swver}-debian" \
          "${swname}-${swver}/debian"

   # change version with code name
   debian_name=$(lsb_release  -sc)
   sed -i "s|{debian_name}|${debian_name}|g"  "${swname}-${swver}/debian/changelog"

}

__install_build_dependencies() {
   apt-get --quiet update \
      && DEBIAN_FRONTEND=noninteractive \
         apt-get install -y \
             debhelper \
             autoconf-archive \
      && rm -rf /var/lib/apt/lists/* \
      && rm -rf /var/cache/apt/archives/*
}

__build_source_code() {
   cd ${swname}-${swver}
   debuild -us -uc
}

__move_packages_to_outdir() {
   mv ../*.{build*,changes,deb,dsc} \
      ../${swname}_${swver}-*.debian.tar.* \
      ../${swname}_${swver}.orig.tar.gz \
      ${outdir}/
}

__cleanall() {
   echo "** - removing temporary build folder ${buildir}/${swname}-${swver} ..."
   rm -fr ${buildir}/${swname}-${swver}
   echo "** - removing sources folder ${swname}-${swver} ..."
   rm -fr ${swname}-${swver}
}
