#!/usr/bin/env bash

# package name
swname="shinken"
# package version
swver="2.4.3"

# build functions

__get_source_code() {
   [ -d "${swname}-${swver}-debian" ] || \
      die "no such folder: $PWD/${swname}-${swver}-debian"

   echo "** - removing the folder ${swname}-${swver} ..."
   rm -fr "${swname}-${swver}"

   echo "** - download ${swname} git repository ..."
   wget http://github.com/naparuba/shinken/archive/${swver}.tar.gz -O ${swname}_${swver}.orig.tar.gz

   tar -zxvf ${swname}_${swver}.orig.tar.gz
   [ -d "${swname}-${swver}" ] || \
      die "no such folder: $PWD/${swname}-${swver}"

   # create the original tarball which is expected by debuild
   #tar -zcf ${swname}_${swver}.orig.tar.gz \
   #         ${swname}-${swver}

   cp -pr "${swname}-${swver}-debian" \
          "${swname}-${swver}/debian"
}

__install_build_dependencies() {
   apt-get --quiet update \
      && DEBIAN_FRONTEND=noninteractive \
         apt-get install -y \
            bash-completion \
            wget \
            python-all  \
            python-psutil \
            python-pycurl \
            python-setuptools  \
            python-cherrypy3 \
      && rm -rf /var/lib/apt/lists/* \
      && rm -rf /var/cache/apt/archives/*
}

__build_source_code() {
   cd ${swname}-${swver}
   debuild -us -uc
}

__move_packages_to_outdir() {
   mv ../*.{build*,changes,deb,dsc} \
      ../${swname}_${swver}*.diff.gz \
      ../${swname}_${swver}.orig.tar.gz \
      ${outdir}/
}

__cleanall() {
   echo "** - removing temporary build folder ${buildir}/${swname}-${swver} ..."
   rm -fr ${buildir}/${swname}-${swver}
   echo "** - removing sources folder ${swname}-${swver} ..."
   rm -fr ${swname}-${swver}
}
